development:

staging:

production:
  react_cors: true
  passphrase: QCW9bszuqaoGREDo
  dashboard_url: 
  core_url: 
  database:
    table: lender
    username: asira_admin
    password: Sky#crest88
    host: 
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: false
    timezone: Asia/Jakarta
  kafka:
    host: 
    port: "9092"
    user: asira_admin
    pass: Sky#crest88
    client_id: asira_lender
    sasl: true
    log_verbose: false
    group_id: asira
    topics:
      produces: asira_backend
      consumes: asira_backend
  jwt:
    duration: 1440 # in minutes
    jwt_secret: ddxnEydnqtNbzatP6Kag
  mailer:
    host : smtp.gmail.com
    port : 587
    email : infra.ayannah@gmail.com 
    password : jakarta2019
  s3:
    debug_mode: 1
    region: id-tbs
    access_key: J2BYZXZ43VPZ27V4TCP3
    secret_key: s0yHeS/eBvjmyshVckbNqVWnTKwhnaP6kYBpFBHk
    host: https://bucket.cloud.lintasarta.co.id:8082
    bucket_name: bucket-ayannah